default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: happenin_development
  host:     localhost
  username: happenin
  password:
  template: template0

test:
  <<: *default
  database: happenin_test
  host:     localhost
  username: happenin
  password:
  template: template0

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  host:     <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  template: template0
